/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface_Outlier;

import Controller_Outlier.Outlier_Controller;
import java.awt.AWTException;
import java.awt.Color;
import java.util.List;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.format.Border;
import jxl.format.BorderLineStyle;
import jxl.format.Colour;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
//import java.util.Calendar;
//import java.util.GregorianCalendar;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    private DefaultTableModel modelData;
    TableColumn column1;
    double simpanjarak[][];

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        modelData = new DefaultTableModel();
        setColor(btn_outlier);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_help, btn_results, btn_profile}, new JPanel[]{ind_2, ind_3, ind_4});
        panel_opening.setVisible(true);
        panel_outlier.setVisible(false);
        panel_result.setVisible(false);
        panel_profile.setVisible(false);
        panel_help.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        jScrollPane1.setBorder(null);

        tabelData.getTableHeader().setOpaque(false);
        tabelData.getTableHeader().setForeground(Color.WHITE);
        tabelData.getTableHeader().setBackground(new java.awt.Color(71, 120, 197));
        tabelData.setEnabled(false);

        tableResult.getTableHeader().setOpaque(false);
        tableResult.getTableHeader().setForeground(Color.WHITE);
        tableResult.getTableHeader().setBackground(new java.awt.Color(71, 120, 197));
        tableResult.setEnabled(false);

        tableDataAsli.getTableHeader().setOpaque(false);
        tableDataAsli.getTableHeader().setForeground(Color.WHITE);
        tableDataAsli.getTableHeader().setBackground(new java.awt.Color(71, 120, 197));
        tableDataAsli.setEnabled(false);

        tableRata2.getTableHeader().setOpaque(false);
        tableRata2.getTableHeader().setForeground(Color.WHITE);
        tableRata2.getTableHeader().setBackground(new java.awt.Color(71, 120, 197));
        tableRata2.setEnabled(false);

        fieldBarisData.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameCekData = new javax.swing.JFrame();
        fieldBrowse1 = new javax.swing.JTextField();
        buttonOpen1 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        panel_tabel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDataAsli = new javax.swing.JTable();
        panel_hide1 = new javax.swing.JPanel();
        side_pane = new javax.swing.JPanel();
        btn_outlier = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        lbl_Outlier = new javax.swing.JLabel();
        lbl_logoOutlier = new javax.swing.JLabel();
        btn_results = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        lbl_Result = new javax.swing.JLabel();
        lbl_LogoResult = new javax.swing.JLabel();
        btn_profile = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        lbl_Profile = new javax.swing.JLabel();
        lbl_LogoProfile = new javax.swing.JLabel();
        btn_help = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        lbl_Help = new javax.swing.JLabel();
        lbl_LogoHelp = new javax.swing.JLabel();
        btn_home = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        icon_logout = new javax.swing.JLabel();
        label_logout = new javax.swing.JLabel();
        lbl_TitleUtama = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panel_opening = new javax.swing.JPanel();
        lbl_logousd = new javax.swing.JLabel();
        lbl_judul1 = new javax.swing.JLabel();
        lbl_judul2 = new javax.swing.JLabel();
        lbl_judul3 = new javax.swing.JLabel();
        panel_outlier = new javax.swing.JPanel();
        fieldBrowse = new javax.swing.JTextField();
        buttonOpen = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panel_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        panel_hide = new javax.swing.JPanel();
        buttonProcess = new javax.swing.JButton();
        lbl_K = new javax.swing.JLabel();
        fieldK = new javax.swing.JTextField();
        lbl_BarisData = new javax.swing.JLabel();
        fieldBarisData = new javax.swing.JTextField();
        lbl_OutlierRank = new javax.swing.JLabel();
        fieldOutlier = new javax.swing.JTextField();
        panel_result = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        lbl_judulResult = new javax.swing.JLabel();
        buttonSORT = new javax.swing.JButton();
        cekButton = new javax.swing.JButton();
        buttonExport = new javax.swing.JButton();
        lbl_clear = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableRata2 = new javax.swing.JTable();
        panel_profile = new javax.swing.JPanel();
        lbl_FotoDiri = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_DataNama = new javax.swing.JLabel();
        lbl_nim = new javax.swing.JLabel();
        lbl_DataNIM = new javax.swing.JLabel();
        lbl_ttl = new javax.swing.JLabel();
        lbl_DataTTL = new javax.swing.JLabel();
        lbl_prodi = new javax.swing.JLabel();
        lbl_DataProdi = new javax.swing.JLabel();
        lbl_fakultas = new javax.swing.JLabel();
        lbl_DataFakultas = new javax.swing.JLabel();
        lbl_universitas = new javax.swing.JLabel();
        lbl_DataUniversitas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel_help = new javax.swing.JPanel();
        panel_help1 = new javax.swing.JPanel();
        lbl_TitleHelp = new javax.swing.JLabel();
        lbl_point1 = new javax.swing.JLabel();
        lbl_point2 = new javax.swing.JLabel();
        lbl_point3 = new javax.swing.JLabel();
        lbl_point4 = new javax.swing.JLabel();
        lbl_point5 = new javax.swing.JLabel();
        lbl_point6 = new javax.swing.JLabel();
        lbl_point7 = new javax.swing.JLabel();
        lbl_point8 = new javax.swing.JLabel();

        buttonOpen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/folder.png"))); // NOI18N
        buttonOpen1.setText("Open");
        buttonOpen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOpen1MouseClicked(evt);
            }
        });

        tableDataAsli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableDataAsli.setToolTipText("");
        tableDataAsli.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tableDataAsli);

        javax.swing.GroupLayout panel_tabel1Layout = new javax.swing.GroupLayout(panel_tabel1);
        panel_tabel1.setLayout(panel_tabel1Layout);
        panel_tabel1Layout.setHorizontalGroup(
            panel_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tabel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE))
        );
        panel_tabel1Layout.setVerticalGroup(
            panel_tabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_hide1Layout = new javax.swing.GroupLayout(panel_hide1);
        panel_hide1.setLayout(panel_hide1Layout);
        panel_hide1Layout.setHorizontalGroup(
            panel_hide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1232, Short.MAX_VALUE)
        );
        panel_hide1Layout.setVerticalGroup(
            panel_hide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jLayeredPane3.setLayer(panel_tabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(panel_hide1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_hide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(panel_tabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panel_hide1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout frameCekDataLayout = new javax.swing.GroupLayout(frameCekData.getContentPane());
        frameCekData.getContentPane().setLayout(frameCekDataLayout);
        frameCekDataLayout.setHorizontalGroup(
            frameCekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCekDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameCekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3)
                    .addGroup(frameCekDataLayout.createSequentialGroup()
                        .addComponent(fieldBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonOpen1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameCekDataLayout.setVerticalGroup(
            frameCekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCekDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameCekDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1370, 730));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_outlier.setBackground(new java.awt.Color(23, 35, 51));
        btn_outlier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_outlierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_outlierMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_Outlier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_Outlier.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Outlier.setText("Outlier");

        lbl_logoOutlier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logoOutlier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/database.png"))); // NOI18N

        javax.swing.GroupLayout btn_outlierLayout = new javax.swing.GroupLayout(btn_outlier);
        btn_outlier.setLayout(btn_outlierLayout);
        btn_outlierLayout.setHorizontalGroup(
            btn_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_outlierLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_logoOutlier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Outlier, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_outlierLayout.setVerticalGroup(
            btn_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Outlier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(ind_1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(lbl_logoOutlier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        side_pane.add(btn_outlier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        btn_results.setBackground(new java.awt.Color(23, 35, 51));
        btn_results.setPreferredSize(new java.awt.Dimension(136, 60));
        btn_results.setRequestFocusEnabled(false);
        btn_results.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resultsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_resultsMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_Result.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_Result.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Result.setText("Results");

        lbl_LogoResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LogoResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/checked.png"))); // NOI18N

        javax.swing.GroupLayout btn_resultsLayout = new javax.swing.GroupLayout(btn_results);
        btn_results.setLayout(btn_resultsLayout);
        btn_resultsLayout.setHorizontalGroup(
            btn_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_resultsLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LogoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_resultsLayout.setVerticalGroup(
            btn_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(lbl_LogoResult, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(lbl_Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(btn_results, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, -1));

        btn_profile.setBackground(new java.awt.Color(23, 35, 51));
        btn_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_profileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_profileMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_Profile.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_Profile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Profile.setText("Profile");

        lbl_LogoProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LogoProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/profile.png"))); // NOI18N

        javax.swing.GroupLayout btn_profileLayout = new javax.swing.GroupLayout(btn_profile);
        btn_profile.setLayout(btn_profileLayout);
        btn_profileLayout.setHorizontalGroup(
            btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_profileLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LogoProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_profileLayout.setVerticalGroup(
            btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_profileLayout.createSequentialGroup()
                .addGroup(btn_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_Profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ind_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lbl_LogoProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        side_pane.add(btn_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 140, -1));

        btn_help.setBackground(new java.awt.Color(23, 35, 51));
        btn_help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_helpMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_helpMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        lbl_Help.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Help.setText("Help");

        lbl_LogoHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LogoHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/information.png"))); // NOI18N

        javax.swing.GroupLayout btn_helpLayout = new javax.swing.GroupLayout(btn_help);
        btn_help.setLayout(btn_helpLayout);
        btn_helpLayout.setHorizontalGroup(
            btn_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_helpLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LogoHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Help, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_helpLayout.setVerticalGroup(
            btn_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_helpLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbl_LogoHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        side_pane.add(btn_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/home-icon-silhouette.png"))); // NOI18N
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });
        side_pane.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 770));

        header.setBackground(new java.awt.Color(71, 120, 197));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        icon_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/logout.png"))); // NOI18N
        icon_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_logoutMouseClicked(evt);
            }
        });

        label_logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_logout.setForeground(new java.awt.Color(255, 255, 255));
        label_logout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_logout.setText("Logout");
        label_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_logoutMouseClicked(evt);
            }
        });

        lbl_TitleUtama.setFont(new java.awt.Font("Melliana Script", 0, 36)); // NOI18N
        lbl_TitleUtama.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TitleUtama.setText("Data Mining (ECODB)  ");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_TitleUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 731, Short.MAX_VALUE)
                .addComponent(label_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_logout)
                .addGap(25, 25, 25))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_TitleUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(icon_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1230, 70));

        lbl_logousd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/logo usd.png"))); // NOI18N

        lbl_judul1.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        lbl_judul1.setText("SISTEM DETEKSI OUTLIER");

        lbl_judul2.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        lbl_judul2.setText("DENGAN MENGGUNAKAN ALGORITMA ECODB");

        lbl_judul3.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        lbl_judul3.setText("(ENHANCED CLASS OUTLIER DISTANCE BASED)");

        javax.swing.GroupLayout panel_openingLayout = new javax.swing.GroupLayout(panel_opening);
        panel_opening.setLayout(panel_openingLayout);
        panel_openingLayout.setHorizontalGroup(
            panel_openingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_openingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_openingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_openingLayout.createSequentialGroup()
                        .addComponent(lbl_judul1)
                        .addGap(444, 444, 444))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_openingLayout.createSequentialGroup()
                        .addComponent(lbl_logousd)
                        .addGap(482, 482, 482))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_openingLayout.createSequentialGroup()
                .addGap(0, 497, Short.MAX_VALUE)
                .addGroup(panel_openingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_judul2)
                    .addComponent(lbl_judul3))
                .addGap(290, 290, 290))
        );
        panel_openingLayout.setVerticalGroup(
            panel_openingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_openingLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_judul1)
                .addGap(49, 49, 49)
                .addComponent(lbl_judul2)
                .addGap(50, 50, 50)
                .addComponent(lbl_judul3)
                .addGap(57, 57, 57)
                .addComponent(lbl_logousd)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        buttonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/folder.png"))); // NOI18N
        buttonOpen.setText("Open");
        buttonOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOpenMouseClicked(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelData.setToolTipText("");
        tabelData.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabelData);

        javax.swing.GroupLayout panel_tabelLayout = new javax.swing.GroupLayout(panel_tabel);
        panel_tabel.setLayout(panel_tabelLayout);
        panel_tabelLayout.setHorizontalGroup(
            panel_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tabelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        panel_tabelLayout.setVerticalGroup(
            panel_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_hideLayout = new javax.swing.GroupLayout(panel_hide);
        panel_hide.setLayout(panel_hideLayout);
        panel_hideLayout.setHorizontalGroup(
            panel_hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        panel_hideLayout.setVerticalGroup(
            panel_hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jLayeredPane2.setLayer(panel_tabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(panel_hide, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap(104, Short.MAX_VALUE)
                    .addComponent(panel_hide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(panel_tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panel_hide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        buttonProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/time-left.png"))); // NOI18N
        buttonProcess.setText("PROCESS");
        buttonProcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonProcessMouseClicked(evt);
            }
        });

        lbl_K.setText("Jumlah Tetangga Terdekat :");

        fieldK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldKKeyTyped(evt);
            }
        });

        lbl_BarisData.setText("Jumlah Baris Data :");

        lbl_OutlierRank.setText("Jumlah Outlier :");

        fieldOutlier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldOutlierKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_outlierLayout = new javax.swing.GroupLayout(panel_outlier);
        panel_outlier.setLayout(panel_outlierLayout);
        panel_outlierLayout.setHorizontalGroup(
            panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_outlierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_outlierLayout.createSequentialGroup()
                        .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_outlierLayout.createSequentialGroup()
                                .addComponent(fieldBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonOpen))
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_outlierLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_K)
                            .addComponent(lbl_OutlierRank))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_outlierLayout.createSequentialGroup()
                                .addComponent(fieldOutlier, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200))
                            .addGroup(panel_outlierLayout.createSequentialGroup()
                                .addComponent(fieldK, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_BarisData)
                                .addGap(18, 18, 18)))
                        .addComponent(fieldBarisData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        panel_outlierLayout.setVerticalGroup(
            panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_outlierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_outlierLayout.createSequentialGroup()
                        .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_outlierLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_K)
                                    .addComponent(fieldK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_BarisData)
                                    .addComponent(fieldBarisData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(panel_outlierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldOutlier, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_OutlierRank)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_result.setLayout(null);

        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "PCL", "PCL(T_K)", "Dev", "KDist", "normDev", "normKDist", "COF"
            }
        ));
        jScrollPane2.setViewportView(tableResult);

        panel_result.add(jScrollPane2);
        jScrollPane2.setBounds(10, 106, 1170, 252);

        lbl_judulResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_judulResult.setText("HASIL IDENTIFIKASI OUTLIER");
        panel_result.add(lbl_judulResult);
        lbl_judulResult.setBounds(440, 20, 325, 29);

        buttonSORT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/sort-by-attributes-interface-button-option.png"))); // NOI18N
        buttonSORT.setText("SORT");
        buttonSORT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSORTMouseClicked(evt);
            }
        });
        panel_result.add(buttonSORT);
        buttonSORT.setBounds(1060, 380, 118, 32);

        cekButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/searching-magnifying-glass.png"))); // NOI18N
        cekButton.setText("CEK");
        cekButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cekButtonMouseClicked(evt);
            }
        });
        panel_result.add(cekButton);
        cekButton.setBounds(1060, 430, 118, 36);

        buttonExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/icon.png"))); // NOI18N
        buttonExport.setText("EXPORT");
        buttonExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExportMouseClicked(evt);
            }
        });
        panel_result.add(buttonExport);
        buttonExport.setBounds(1060, 480, 118, 38);

        lbl_clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_clear.setText("Clear (X)");
        lbl_clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clearMouseClicked(evt);
            }
        });
        panel_result.add(lbl_clear);
        lbl_clear.setBounds(1110, 70, 62, 27);

        tableRata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TINGKAT MATKUL", "BIDANG 1", "BIDANG 2", "BIDANG 3", "BIDANG 4", "BIDANG 5", "BIDANG 6"
            }
        ));
        tableRata2.setEnabled(false);
        jScrollPane3.setViewportView(tableRata2);

        panel_result.add(jScrollPane3);
        jScrollPane3.setBounds(10, 395, 690, 80);

        lbl_FotoDiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface_Outlier/images/foto profil program.png"))); // NOI18N

        lbl_nama.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_nama.setText("NAMA");

        lbl_DataNama.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataNama.setText("YULIUS ELFRISA DESANCOKO");

        lbl_nim.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_nim.setText("NIM");

        lbl_DataNIM.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataNIM.setText("155314040");

        lbl_ttl.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_ttl.setText("TEMPAT, TANGGAL LAHIR");

        lbl_DataTTL.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataTTL.setText("PONOROGO, 14 AGUSTUS 1996");

        lbl_prodi.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_prodi.setText("PROGRAM STUDI");

        lbl_DataProdi.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataProdi.setText("TEKNIK INFORMATIKA");

        lbl_fakultas.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_fakultas.setText("FAKULTAS");

        lbl_DataFakultas.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataFakultas.setText("FAKULTAS SAINS DAN TEKNOLOGI");

        lbl_universitas.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_universitas.setText("UNIVERSITAS");

        lbl_DataUniversitas.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        lbl_DataUniversitas.setText("UNIVERSITAS SANATA DHARMA");

        jLabel1.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel1.setText(":");

        jLabel6.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel6.setText(":");

        jLabel19.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel20.setText(":");

        jLabel21.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel21.setText(":");

        jLabel22.setFont(new java.awt.Font("Skeleton Type One Poster Bold", 0, 24)); // NOI18N
        jLabel22.setText(":");

        javax.swing.GroupLayout panel_profileLayout = new javax.swing.GroupLayout(panel_profile);
        panel_profile.setLayout(panel_profileLayout);
        panel_profileLayout.setHorizontalGroup(
            panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_profileLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_FotoDiri)
                .addGap(104, 104, 104)
                .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_profileLayout.createSequentialGroup()
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fakultas)
                            .addComponent(lbl_universitas))
                        .addGap(79, 79, 79)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)))
                    .addGroup(panel_profileLayout.createSequentialGroup()
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ttl)
                            .addComponent(lbl_prodi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)))
                    .addGroup(panel_profileLayout.createSequentialGroup()
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nim)
                            .addComponent(lbl_nama))
                        .addGap(133, 133, 133)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))))
                .addGap(30, 30, 30)
                .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DataNama)
                    .addComponent(lbl_DataUniversitas)
                    .addComponent(lbl_DataFakultas)
                    .addComponent(lbl_DataProdi)
                    .addComponent(lbl_DataTTL)
                    .addComponent(lbl_DataNIM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_profileLayout.setVerticalGroup(
            panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_profileLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_profileLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nama)
                            .addComponent(jLabel1)
                            .addComponent(lbl_DataNama))
                        .addGap(35, 35, 35)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nim)
                            .addComponent(jLabel6)
                            .addComponent(lbl_DataNIM))
                        .addGap(37, 37, 37)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_DataTTL)
                            .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_ttl)
                                .addComponent(jLabel19)))
                        .addGap(45, 45, 45)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prodi)
                            .addComponent(jLabel20)
                            .addComponent(lbl_DataProdi))
                        .addGap(49, 49, 49)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fakultas)
                            .addComponent(jLabel21)
                            .addComponent(lbl_DataFakultas))
                        .addGap(45, 45, 45)
                        .addGroup(panel_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_universitas)
                            .addComponent(jLabel22)
                            .addComponent(lbl_DataUniversitas)))
                    .addComponent(lbl_FotoDiri))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        lbl_TitleHelp.setFont(new java.awt.Font("Cinzel Decorative", 1, 24)); // NOI18N
        lbl_TitleHelp.setText("PANDUAN CARA PENGGUNAAN APLIKASI");

        lbl_point1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point1.setText("1. Klik menu Outlier pada side bar menu");

        lbl_point2.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point2.setText("2. Setelah itu pada halaman Outlier klik tombol Open untuk membuka file bertipe .xls  ");

        lbl_point3.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point3.setText("3. Jika data dengan format .xls telah berhasil muncul pada tabel pada halaman Outlier, masukkan nilai K dan jumlah  outlier");

        lbl_point4.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point4.setText("4. Setelah itu jika sudah tekan tombol Process untuk menjalankan algoritma Enhanced Class Outlier Distance Based (ECODB)");

        lbl_point5.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point5.setText("5. Selanjutnya, klik menu Result pada side bar menu, maka akan menampilkan hasil dari PCL, PCL(T_K), Dev, KDist, normDev, normKDist, dan COF");

        lbl_point6.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point6.setText("6. Lalu klik tombol SORT pada halaman Result untuk mengurutkan hasil COF dari yang terkecil hingga terbesar");

        lbl_point7.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point7.setText("7. Klik tombol CHECK untuk menampilkan data asli untuk membandingkan hasil  yang diperoleh");

        lbl_point8.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lbl_point8.setText("8. Klik tombol EXPORT untuk mengekspor hasil algoritma ECODB ke dalam bentuk format .xls");

        javax.swing.GroupLayout panel_help1Layout = new javax.swing.GroupLayout(panel_help1);
        panel_help1.setLayout(panel_help1Layout);
        panel_help1Layout.setHorizontalGroup(
            panel_help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_help1Layout.createSequentialGroup()
                .addGroup(panel_help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_help1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel_help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_point2)
                            .addComponent(lbl_point1)
                            .addComponent(lbl_point3)
                            .addComponent(lbl_point4)
                            .addComponent(lbl_point5)
                            .addComponent(lbl_point6)
                            .addComponent(lbl_point7)
                            .addComponent(lbl_point8)))
                    .addGroup(panel_help1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(lbl_TitleHelp)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panel_help1Layout.setVerticalGroup(
            panel_help1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_help1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_TitleHelp)
                .addGap(63, 63, 63)
                .addComponent(lbl_point1)
                .addGap(18, 18, 18)
                .addComponent(lbl_point2)
                .addGap(18, 18, 18)
                .addComponent(lbl_point3)
                .addGap(18, 18, 18)
                .addComponent(lbl_point4)
                .addGap(18, 18, 18)
                .addComponent(lbl_point5)
                .addGap(18, 18, 18)
                .addComponent(lbl_point6)
                .addGap(18, 18, 18)
                .addComponent(lbl_point7)
                .addGap(18, 18, 18)
                .addComponent(lbl_point8)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_helpLayout = new javax.swing.GroupLayout(panel_help);
        panel_help.setLayout(panel_helpLayout);
        panel_helpLayout.setHorizontalGroup(
            panel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1356, Short.MAX_VALUE)
            .addGroup(panel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_helpLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_help1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_helpLayout.setVerticalGroup(
            panel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(panel_helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_helpLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_help1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jLayeredPane1.setLayer(panel_opening, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel_outlier, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel_result, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel_profile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panel_help, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_outlier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_opening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_outlier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_help, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_opening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 1230, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_outlierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outlierMousePressed
        // TODO add your handling code here:
        setColor(btn_outlier);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_help, btn_results, btn_profile}, new JPanel[]{ind_2, ind_3, ind_4});
    }//GEN-LAST:event_btn_outlierMousePressed

    private void btn_resultsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resultsMousePressed
        // TODO add your handling code here:
        setColor(btn_results);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_help, btn_outlier, btn_profile}, new JPanel[]{ind_2, ind_1, ind_4});
    }//GEN-LAST:event_btn_resultsMousePressed

    private void btn_profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMousePressed
        // TODO add your handling code here:
        setColor(btn_profile);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_help, btn_results, btn_outlier}, new JPanel[]{ind_2, ind_3, ind_1});
    }//GEN-LAST:event_btn_profileMousePressed

    private void btn_helpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_helpMouseReleased
        // TODO add your handling code here:
        setColor(btn_help);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_outlier, btn_results, btn_profile}, new JPanel[]{ind_1, ind_3, ind_4});
    }//GEN-LAST:event_btn_helpMouseReleased

    int xx, xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerMouseDragged

    private void btn_outlierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outlierMouseClicked
        panel_outlier.setVisible(true);
        panel_result.setVisible(false);
        panel_profile.setVisible(false);
        panel_help.setVisible(false);
    }//GEN-LAST:event_btn_outlierMouseClicked

    private void btn_resultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resultsMouseClicked
        panel_outlier.setVisible(false);
        panel_result.setVisible(true);
        panel_profile.setVisible(false);
        panel_help.setVisible(false);
    }//GEN-LAST:event_btn_resultsMouseClicked

    private void icon_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_logoutMouseClicked
        this.dispose();
    }//GEN-LAST:event_icon_logoutMouseClicked

    private void label_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_logoutMouseClicked
        this.dispose();
    }//GEN-LAST:event_label_logoutMouseClicked

    private void btn_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_profileMouseClicked
        panel_outlier.setVisible(false);
        panel_result.setVisible(false);
        panel_profile.setVisible(true);
        panel_help.setVisible(false);
    }//GEN-LAST:event_btn_profileMouseClicked

    private void btn_helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_helpMouseClicked
        panel_outlier.setVisible(false);
        panel_result.setVisible(false);
        panel_profile.setVisible(false);
        panel_help.setVisible(true);
    }//GEN-LAST:event_btn_helpMouseClicked

    private void buttonOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOpenMouseClicked
        try {
            panel_outlier.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            JFileChooser pilihfile = new JFileChooser();
//        pilihfile.setFileFilter(new FileNameExtensionFilter("xls"));
            int option = pilihfile.showOpenDialog(this);
            panel_outlier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            File excel = pilihfile.getSelectedFile().getAbsoluteFile();
            String namafile = excel.getAbsolutePath();

            if (option == JFileChooser.APPROVE_OPTION) {

                if (!namafile.endsWith("xls")) {
                    JOptionPane.showMessageDialog(null, "Pilih File Berekstensi .xls", "WANING", JOptionPane.ERROR_MESSAGE);

                } else {
                    fieldBrowse.setText(namafile);
                    File excelFile = new File(namafile);
                    try {

                        Workbook workbook = Workbook.getWorkbook(excelFile);
                        Sheet sheet = workbook.getSheets()[0];

                        TableModel model = new DefaultTableModel(sheet.getRows(), sheet.getColumns());
                        for (int row = 0; row < sheet.getRows(); row++) {
                            for (int column = 0; column < sheet.getColumns(); column++) {
                                String content = sheet.getCell(column, row).getContents();
                                model.setValueAt(content, row, column);
                            }
                        }
                        tabelData.setModel(model);

                        //ubah nama kolom tabel
                        for (int x = 0; x < tabelData.getColumnCount(); x++) {
                            column1 = tabelData.getTableHeader().getColumnModel().getColumn(x);
                            column1.setHeaderValue((String) tabelData.getValueAt(0, x));
                        }
                        ((DefaultTableModel) tabelData.getModel()).removeRow(0);

                        panel_hide.setVisible(false);
                        panel_tabel.setVisible(true);

//                    System.out.println(jTable1.getRowCount());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Gagal Membuka File", "WARNING", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                    }
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_buttonOpenMouseClicked
    private static int[][] cek;

    public static int[][] getCek() {
        return cek;
    }

    public void setCek(int[][] cek) {
        this.cek = cek;
    }
    
    
    private void buttonProcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonProcessMouseClicked
        String nilaiK = fieldK.getText();
        String nilaiOutlier = fieldOutlier.getText();
        if (nilaiK.length() == 0 && nilaiOutlier.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai K dan Jumlah Outlier ", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (nilaiOutlier.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukkan jumlah nilai outlier", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else if (nilaiK.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukkan nilai K", "WARNING", JOptionPane.ERROR_MESSAGE);
        } else {

            cek = new int[tabelData.getRowCount()][tabelData.getColumnCount()];
            for (int l = 0; l < tabelData.getRowCount(); l++) {
                for (int j = 0; j < tabelData.getColumnCount(); j++) {
                    cek[l][j] = Integer.parseInt(tabelData.getValueAt(l, 1).toString());
//                    System.out.print(cek[l][j] + " ");
                }
                System.out.println(cek[l][1]);
            }
            System.out.println("");

            //Mengambil data dari excel
            double data[][] = new double[tabelData.getRowCount()][tabelData.getColumnCount() - 1];
            simpanjarak = new double[tabelData.getRowCount()][tabelData.getRowCount()];
            for (int i = 0; i < tabelData.getRowCount(); i++) {
                int z = 1;
                for (int j = 0; j < tabelData.getColumnCount() - 1; j++) {
                    data[i][j] = Double.parseDouble(tabelData.getValueAt(i, z).toString());
                    z = z + 1;
//                System.out.print(data[i][j] + " ");
                }
            }

            int barisData = tabelData.getRowCount();
            fieldBarisData.setText(Integer.toString(barisData));

            Outlier_Controller oc = new Outlier_Controller();
            LinkedList temp = new LinkedList();
            for (int i = 0; i < data.length; i++) {
                if (i == 0) {
                    temp.add("" + data[i][0]);
                } else {
                    boolean ketemu = false;
                    for (int j = 0; j < temp.size(); j++) {
                        if (Double.parseDouble(temp.get(j).toString()) == data[i][0]) {
                            ketemu = true;
                        }
                    }
                    if (!ketemu) {
                        temp.add("" + data[i][0]);
                    }
                }
            }
            //Array of LinkedList
            LinkedList[] test = new LinkedList[temp.size()];
            for (int i = 0; i < test.length; i++) {
                test[i] = new LinkedList();
                for (int j = 0; j < data.length; j++) {
                    if (Double.parseDouble(temp.get(i).toString()) == data[j][0]) {
                        test[i].add(j);
                    }
                }
            }
            System.out.println(test[0]);
            for (int i = 0; i < test.length; i++) {
                System.out.println(test[i]);
            }

            System.out.println("");
            for (int i = 0; i < data.length; i++) {
                for (int j = 0; j < data.length; j++) {
                    simpanjarak[i][j] = oc.EuclideanDistance(data, i, j);
//                System.out.println("jarak " + i + " - " + j + " : " + simpanjarak[i][j]);
                    System.out.print(simpanjarak[i][j] + " ");
                }
                System.out.println(" ");
            }
            System.out.println("");
            
            int K = Integer.parseInt(fieldK.getText());
            double[][] hasil = oc.PCL_DEV_Kdist(simpanjarak, temp, data, test, K);
            double[] pcl_T = new double[simpanjarak.length];
            double[] pcl = new double[simpanjarak.length];
            double[] deviasi = new double[simpanjarak.length];
            double[] kdist = new double[simpanjarak.length];
            double maxDev, minDev, maxKDist, minKDist;
            double normDev = 0, normKDist = 0;
            double COF = 0;

            System.out.println("");
            System.out.println("");
            for (int i = 0; i < hasil.length; i++) {
                deviasi[i] = hasil[i][2];
                kdist[i] = hasil[i][3];
                System.out.println(Arrays.toString(hasil[i]));
            }
            System.out.println("");

            System.out.println("Max dan Min Deviation");
            maxDev = Double.valueOf(oc.Max(deviasi));
            System.out.println(maxDev);
            minDev = Double.valueOf(oc.Min(deviasi));
            System.out.println(minDev);
            System.out.println("=====================");
            System.out.println("");

            System.out.println("Max dan Min KDist");
            maxKDist = Double.valueOf(oc.Max(kdist));
            System.out.println(maxKDist);
            minKDist = Double.valueOf(oc.Min(kdist));
            System.out.println(minKDist);
            System.out.println("=====================");
            System.out.println("");

            double dev = 0, kD = 0, pc = 0, p = 0;

            DefaultTableModel model = (DefaultTableModel) tableResult.getModel();
            DecimalFormat format = new DecimalFormat("#0");
            List<Double> d = null;
            for (int i = 0; i < hasil.length; i++) {
                pcl[i] = hasil[i][0];
                pcl_T[i] = hasil[i][1];
//            oc.sort(hasil, 1);
                deviasi[i] = hasil[i][2];
                kdist[i] = hasil[i][3];

                p = pcl[i];
                dev = deviasi[i];
                normDev = Double.valueOf(oc.normDeviation(dev, maxDev, minDev));
                kD = kdist[i];
                normKDist = Double.valueOf(oc.normKDist(kD, maxKDist, minKDist));
                pc = pcl_T[i];
                COF = Double.valueOf(oc.COF(pc, normDev, normKDist, K));
                double no = i + 1;

                System.out.println("");
                System.out.println("");

                d = new ArrayList<Double>();
                d.add(no);
                d.add(p);
                d.add(pc);
                d.add(dev);
                d.add(kD);
                d.add(normDev);
                d.add(normKDist);
                d.add(COF);
                ;

                double aPCL, bPCL_TK, cDev, dKDist, eNormDev, fNormKDist, gCOF, hNo;
                hNo = d.get(0);
                aPCL = d.get(1);
                bPCL_TK = d.get(2);
                cDev = d.get(3);
                dKDist = d.get(4);
                eNormDev = d.get(5);
                fNormKDist = d.get(6);
                gCOF = d.get(7);

                model.addRow(new Object[]{format.format(hNo), aPCL, bPCL_TK, cDev, dKDist, eNormDev, fNormKDist, gCOF});

            }
        }
    }//GEN-LAST:event_buttonProcessMouseClicked


    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        panel_opening.setVisible(true);
        panel_outlier.setVisible(false);
        panel_result.setVisible(false);
        panel_profile.setVisible(false);
        panel_help.setVisible(false);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void buttonOpen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOpen1MouseClicked
        try {
            frameCekData.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            JFileChooser pilihfile = new JFileChooser();

            int option = pilihfile.showOpenDialog(this);
            frameCekData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            File excel = pilihfile.getSelectedFile().getAbsoluteFile();
            String namafile = excel.getAbsolutePath();

            if (option == JFileChooser.APPROVE_OPTION) {

                if (!namafile.endsWith("xls")) {
                    JOptionPane.showMessageDialog(null, "Pilih file berekstensi .xls", "WARNING", JOptionPane.ERROR_MESSAGE);

                } else {
                    fieldBrowse1.setText(namafile);
                    File excelFile = new File(namafile);
                    try {

                        Workbook workbook = Workbook.getWorkbook(excelFile);
                        Sheet sheet = workbook.getSheets()[0];

                        TableModel model = new DefaultTableModel(sheet.getRows(), sheet.getColumns());
                        for (int row = 0; row < sheet.getRows(); row++) {
                            for (int column = 0; column < sheet.getColumns(); column++) {
                                String content = sheet.getCell(column, row).getContents();
                                model.setValueAt(content, row, column);
                            }
                        }
                        tableDataAsli.setModel(model);

                        //ubah nama kolom tabel
                        for (int x = 0; x < tableDataAsli.getColumnCount(); x++) {
                            column1 = tableDataAsli.getTableHeader().getColumnModel().getColumn(x);
                            column1.setHeaderValue((String) tableDataAsli.getValueAt(0, x));
                        }
                        ((DefaultTableModel) tabelData.getModel()).removeRow(0);

                        panel_hide1.setVisible(false);
                        panel_tabel1.setVisible(true);

//                    System.out.println(jTable1.getRowCount());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Gagal Membuka File", "WARNING", JOptionPane.ERROR_MESSAGE);

                        e.printStackTrace();
                    }
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_buttonOpen1MouseClicked

    private void fieldKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_fieldKKeyTyped

    private void fieldOutlierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldOutlierKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();

        }
    }//GEN-LAST:event_fieldOutlierKeyTyped

    private void lbl_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clearMouseClicked
        DefaultTableModel model = (DefaultTableModel) tableResult.getModel();
        fieldBarisData.setText(null);
        int baris = tableResult.getRowCount();
        for (int i = 0; i < baris; i++) {
            model.removeRow(0);
        }
    }//GEN-LAST:event_lbl_clearMouseClicked

    private void buttonExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExportMouseClicked
        try {
            JFileChooser export = new JFileChooser();
            export.setDialogTitle("Export File");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("xls", "xls");
            export.setFileFilter(filter);
            if (export.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {

                String pilih = export.getSelectedFile().toString().concat(".xls");
                File excel = new File(pilih);

                if (excel.exists()) {
                    JOptionPane.showMessageDialog(null, "Data sudah ada, silahkan isi dengan nama yang lain", "WARNING", JOptionPane.ERROR_MESSAGE);
                } else {
                    WritableWorkbook workbook1 = Workbook.createWorkbook(excel);
                    WritableSheet sheet1 = workbook1.createSheet("Data Identifikasi Outlier", 0);
                    TableModel hasilResult = tableResult.getModel();

                    WritableCellFormat body = new WritableCellFormat();
                    body.setBorder(Border.ALL, BorderLineStyle.THIN);
                    WritableCellFormat header = new WritableCellFormat();
                    header.setBackground(Colour.AQUA);
                    header.setBorder(Border.ALL, BorderLineStyle.THIN);

                    Label judul1 = new Label(2, 0, lbl_judulResult.getText());
                    Label judul2 = new Label(2, 1, lbl_DataFakultas.getText());
                    Label judul3 = new Label(2, 2, lbl_DataUniversitas.getText());
                    sheet1.addCell(judul1);
                    sheet1.addCell(judul2);
                    sheet1.addCell(judul3);

                    Label barData = new Label(0, 4, "Jumlah Baris Data : " + fieldBarisData.getText());
                    Label K = new Label(0, 5, "Jumlah Tetangga Terdekat : " + fieldK.getText());
                    Label rankOutlier = new Label(0, 6, "Jumlah Outlier : " + fieldOutlier.getText());
                    sheet1.addCell(barData);
                    sheet1.addCell(K);
                    sheet1.addCell(rankOutlier);
                    //
                    Label no = new Label(0, 8, "No.", header);
                    Label pcl = new Label(1, 8, "PCL", header);
                    Label pcl_tk = new Label(2, 8, "PCL(T_K)", header);
                    Label dev = new Label(3, 8, "Dev", header);
                    Label kdist = new Label(4, 8, "KDist", header);
                    Label normDev = new Label(5, 8, "NormDev", header);
                    Label normKDist = new Label(6, 8, "NormKDist", header);
                    Label cof = new Label(7, 8, "COF", header);
                    sheet1.addCell(no);
                    sheet1.addCell(pcl);
                    sheet1.addCell(pcl_tk);
                    sheet1.addCell(dev);
                    sheet1.addCell(kdist);
                    sheet1.addCell(normDev);
                    sheet1.addCell(normKDist);
                    sheet1.addCell(cof);

                    for (int i = 0; i < hasilResult.getRowCount(); i++) {
                        for (int j = 0; j < hasilResult.getColumnCount(); j++) {
                            Label row = new Label(j, i + 9, hasilResult.getValueAt(i, j).toString(), body);
                            sheet1.addCell(row);
                        }
                        System.out.println("");
                    }
                    workbook1.write();
                    workbook1.close();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "SUCSESS", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal Mengekspor File", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonExportMouseClicked

    private void cekButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cekButtonMouseClicked
        frameCekData.setExtendedState(MAXIMIZED_BOTH);
        frameCekData.setVisible(true);
        Outlier_Controller oc = new Outlier_Controller();
        DecimalFormat format = new DecimalFormat("#0.00");
        double cek[][] = new double[tabelData.getRowCount()][tabelData.getColumnCount()];
        for (int l = 0; l < tabelData.getRowCount(); l++) {
            for (int j = 0; j < tabelData.getColumnCount(); j++) {
                cek[l][j] = Double.parseDouble(tabelData.getValueAt(l, j).toString());
                System.out.print(cek[l][j] + " ");
            }
            System.out.println("");
        }

        oc.sort(cek, 1);
        System.out.println();

        double rrata[][] = new double[3][6];
        int counter1 = 0;
        int counter2 = 0;
        int counter3 = 0;
        for (int l = 0; l < cek.length; l++) {
            for (int j = 0; j < 1; j++) {
                if (cek[l][1] == 1) {
                    rrata[0][0] = rrata[0][0] + cek[l][2];
                    rrata[0][1] = rrata[0][1] + cek[l][3];
                    rrata[0][2] = rrata[0][2] + cek[l][4];
                    rrata[0][3] = rrata[0][3] + cek[l][5];
                    rrata[0][4] = rrata[0][4] + cek[l][6];
                    rrata[0][5] = rrata[0][5] + cek[l][7];
                    counter1 = counter1 + 1;
                }
                if (cek[l][1] == 2) {
                    rrata[1][0] = rrata[1][0] + cek[l][2];
                    rrata[1][1] = rrata[1][1] + cek[l][3];
                    rrata[1][2] = rrata[1][2] + cek[l][4];
                    rrata[1][3] = rrata[1][3] + cek[l][5];
                    rrata[1][4] = rrata[1][4] + cek[l][6];
                    rrata[1][5] = rrata[1][5] + cek[l][7];
                    counter2 = counter2 + 1;
                }
                if (cek[l][1] == 3) {
                    rrata[2][0] = rrata[2][0] + cek[l][2];
                    rrata[2][1] = rrata[2][1] + cek[l][3];
                    rrata[2][2] = rrata[2][2] + cek[l][4];
                    rrata[2][3] = rrata[2][3] + cek[l][5];
                    rrata[2][4] = rrata[2][4] + cek[l][6];
                    rrata[2][5] = rrata[2][5] + cek[l][7];
                    counter3 = counter3 + 1;
                }

            }
            System.out.println("");
        }
        double tm1b1 = Double.parseDouble(format.format(rrata[0][0] / counter1));
        double tm2b1 = Double.parseDouble(format.format(rrata[1][0] / counter2));
        double tm3b1 = Double.parseDouble(format.format(rrata[2][0] / counter3));

        double tm1b2 = Double.parseDouble(format.format(rrata[0][1] / counter1));
        double tm2b2 = Double.parseDouble(format.format(rrata[1][1] / counter2));
        double tm3b2 = Double.parseDouble(format.format(rrata[2][1] / counter3));

        double tm1b3 = Double.parseDouble(format.format(rrata[0][2] / counter1));
        double tm2b3 = Double.parseDouble(format.format(rrata[1][2] / counter2));
        double tm3b3 = Double.parseDouble(format.format(rrata[2][2] / counter3));

        double tm1b4 = Double.parseDouble(format.format(rrata[0][3] / counter1));
        double tm2b4 = Double.parseDouble(format.format(rrata[1][3] / counter2));
        double tm3b4 = Double.parseDouble(format.format(rrata[2][3] / counter3));

        double tm1b5 = Double.parseDouble(format.format(rrata[0][4] / counter1));
        double tm2b5 = Double.parseDouble(format.format(rrata[1][4] / counter2));
        double tm3b5 = Double.parseDouble(format.format(rrata[2][4] / counter3));

        double tm1b6 = Double.parseDouble(format.format(rrata[0][5] / counter1));
        double tm2b6 = Double.parseDouble(format.format(rrata[1][5] / counter2));
        double tm3b6 = Double.parseDouble(format.format(rrata[2][5] / counter3));

        double tingkat1 = 1, tingkat2 = 2, tingkat3 = 3;

        DefaultTableModel model = (DefaultTableModel) tableRata2.getModel();
        model.addRow(new Object[]{tingkat1, tm1b1, tm1b2, tm1b3, tm1b4, tm1b5, tm1b6});
        model.addRow(new Object[]{tingkat2, tm2b1, tm2b2, tm2b3, tm2b4, tm2b5, tm2b6});
        model.addRow(new Object[]{tingkat3, tm3b1, tm3b2, tm3b3, tm3b4, tm3b5, tm3b6});

    }//GEN-LAST:event_cekButtonMouseClicked

    private void buttonSORTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSORTMouseClicked
        double hasil_outlier[][] = new double[tableResult.getRowCount()][tableResult.getColumnCount()];
        for (int l = 0; l < tableResult.getRowCount(); l++) {
            for (int j = 0; j < tableResult.getColumnCount(); j++) {
                hasil_outlier[l][j] = Double.parseDouble(tableResult.getValueAt(l, j).toString());
                System.out.print(hasil_outlier[l][j] + " ");
            }
            System.out.println("");
        }

        System.out.println("");
        Outlier_Controller oc = new Outlier_Controller();
        oc.sort(hasil_outlier, 7);
        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "No.", "PCL", "PCL(T_K)", "Dev", "KDist", "normDev", "normKDist", "COF"
                }
        );

        for (int i = 0; i < hasil_outlier.length; i++) {
            String[] row = new String[hasil_outlier[i].length];
            for (int j = 0; j < hasil_outlier[i].length; j++) {
                if (j == 0) {
                    row[j] = "" + (int) hasil_outlier[i][j];
                } else {
                    row[j] = "" + hasil_outlier[i][j];
                }
                System.out.print(hasil_outlier[i][j] + " ");
            }
            //
            System.out.println("");
            model.addRow(row);
        }
        int z = Integer.parseInt(fieldOutlier.getText());
        int baris = model.getRowCount();
        for (int l = baris - 1; l > z - 1; l--) {
            model.removeRow(l);
        }
        tableResult.setModel(model);
    }//GEN-LAST:event_buttonSORTMouseClicked

//    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_help;
    private javax.swing.JLabel btn_home;
    private javax.swing.JPanel btn_outlier;
    private javax.swing.JPanel btn_profile;
    private javax.swing.JPanel btn_results;
    private javax.swing.JButton buttonExport;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonOpen1;
    private javax.swing.JButton buttonProcess;
    private javax.swing.JButton buttonSORT;
    private javax.swing.JButton cekButton;
    private javax.swing.JTextField fieldBarisData;
    private javax.swing.JTextField fieldBrowse;
    private javax.swing.JTextField fieldBrowse1;
    private javax.swing.JTextField fieldK;
    private javax.swing.JTextField fieldOutlier;
    private javax.swing.JFrame frameCekData;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icon_logout;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_logout;
    private javax.swing.JLabel lbl_BarisData;
    private javax.swing.JLabel lbl_DataFakultas;
    private javax.swing.JLabel lbl_DataNIM;
    private javax.swing.JLabel lbl_DataNama;
    private javax.swing.JLabel lbl_DataProdi;
    private javax.swing.JLabel lbl_DataTTL;
    private javax.swing.JLabel lbl_DataUniversitas;
    private javax.swing.JLabel lbl_FotoDiri;
    private javax.swing.JLabel lbl_Help;
    private javax.swing.JLabel lbl_K;
    private javax.swing.JLabel lbl_LogoHelp;
    private javax.swing.JLabel lbl_LogoProfile;
    private javax.swing.JLabel lbl_LogoResult;
    private javax.swing.JLabel lbl_Outlier;
    private javax.swing.JLabel lbl_OutlierRank;
    private javax.swing.JLabel lbl_Profile;
    private javax.swing.JLabel lbl_Result;
    private javax.swing.JLabel lbl_TitleHelp;
    private javax.swing.JLabel lbl_TitleUtama;
    private javax.swing.JLabel lbl_clear;
    private javax.swing.JLabel lbl_fakultas;
    private javax.swing.JLabel lbl_judul1;
    private javax.swing.JLabel lbl_judul2;
    private javax.swing.JLabel lbl_judul3;
    private javax.swing.JLabel lbl_judulResult;
    private javax.swing.JLabel lbl_logoOutlier;
    private javax.swing.JLabel lbl_logousd;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nim;
    private javax.swing.JLabel lbl_point1;
    private javax.swing.JLabel lbl_point2;
    private javax.swing.JLabel lbl_point3;
    private javax.swing.JLabel lbl_point4;
    private javax.swing.JLabel lbl_point5;
    private javax.swing.JLabel lbl_point6;
    private javax.swing.JLabel lbl_point7;
    private javax.swing.JLabel lbl_point8;
    private javax.swing.JLabel lbl_prodi;
    private javax.swing.JLabel lbl_ttl;
    private javax.swing.JLabel lbl_universitas;
    private javax.swing.JPanel panel_help;
    private javax.swing.JPanel panel_help1;
    private javax.swing.JPanel panel_hide;
    private javax.swing.JPanel panel_hide1;
    private javax.swing.JPanel panel_opening;
    private javax.swing.JPanel panel_outlier;
    private javax.swing.JPanel panel_profile;
    private javax.swing.JPanel panel_result;
    private javax.swing.JPanel panel_tabel;
    private javax.swing.JPanel panel_tabel1;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTable tabelData;
    private javax.swing.JTable tableDataAsli;
    private javax.swing.JTable tableRata2;
    private javax.swing.JTable tableResult;
    // End of variables declaration//GEN-END:variables
}
